/*
    Copyright 2024, 2025, 2026 David Healey

    This file is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This file is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with This file. If not, see <http://www.gnu.org/licenses/>.
*/

namespace Shell
{
	const numSourceChannels = Synth.getRoutingMatrix(Synth.getIdList("Container")[0]).getNumSourceChannels();
	const channelIndexes = [];
	
	for (i = 0; i < numSourceChannels; i++)
		channelIndexes.push(i);
		
	LayoutBuilder.add([
		{
			"type": "ScriptPanel",
			"id": "pnlMain",
			"x": 0.0,
			"y": 0.0,
			"bgColour": 0x0,
			"itemColour": 0x0,
			"itemColour2": 0x0,
			"textColour": 0x0,
			"width":  Content.getInterfaceSize()[0],
			"height":  Content.getInterfaceSize()[1],
			"locked": "1",
			"childComponents": [
				{
					"type": "ScriptPanel",
					"id": "pnlHeader",
					"text": "Rhapsodist",
					"x": 0.0,
					"y": 0.0,
					"width": 1000.0,
					"height": 50.0,
					"bgColour": 0xff181825,
					"textColour": 0xffcdd6f4,
					"parentComponent": "pnlMain",
					"locked": "1",
					"childComponents": [
						{
							"type": "ScriptSlider",
							"id": "knbPatch",
							"x": 0.0,
							"y": 0.0,
							"width": 100.0,
							"height": 50.0,
							"parentComponent": "pnlHeader",
							"max": 100.0,
							"stepSize": 1.0,
							"middlePosition": 50.0,
							"enableMidiLearn": "0",
							"visible": "0",
							"locked": "1"
						},
						{
							"type": "ScriptSlider",
							"id": "knbArticulation",
							"x": 100.0,
							"y": 0.0,
							"width": 100.0,
							"height": 50.0,
							"parentComponent": "pnlHeader",
							"max": 100.0,
							"stepSize": 1.0,
							"middlePosition": 50.0,
							"enableMidiLearn": "0",
							"visible": "0",
							"locked": "1"
						},
						{
							"type": "ScriptPanel",
							"id": "pnlPresetDisplay",
							"x": 325.0,
							"y": 10.0,
							"width": 350.0,
							"height": 30.0,
							"bgColour": 0xff11111b,
							"textColour": 0xffcdd6f4,
							"parentComponent": "pnlHeader",
							"locked": "1",
							"childComponents": [
								{
									"type": "ScriptButton",
									"id": "btnPresetBrowser",
									"text": "Presets",
									"x": 0.0,
									"y": 0.0,
									"width": 289.0,
									"height": 30.0,
									"textColour": 0xffcdd6f4,
									"parentComponent": "pnlPresetDisplay",
									"saveInPreset": false,
									"tooltip": "Click to Open Preset Browser",
									"locked": "1",
									"enableMidiLearn": "0"
								},
								{
									"type": "ScriptButton",
									"id": "btnPreset0",
									"text": "e138",
									"x": 285.0,
									"y": 0.0,
									"width": 17.0,
									"height": 30.0,
									"textColour": 0xffcdd6f4,
									"parentComponent": "pnlPresetDisplay",
									"saveInPreset": "0",
									"isMomentary": "1",
									"tooltip": "Load Previous Preset",
									"locked": "1",
									"enableMidiLearn": "0"
								},
								{
									"type": "ScriptButton",
									"id": "btnPreset1",
									"text": "e13a",
									"x": 303.0,
									"y": 0.0,
									"width": 17.0,
									"height": 30.0,
									"textColour": 0xffcdd6f4,
									"parentComponent": "pnlPresetDisplay",
									"saveInPreset": "0",
									"isMomentary": "1",
									"tooltip": "Load Next Preset",
									"locked": "1",
									"enableMidiLearn": "0"
								},
								{
									"type": "ScriptButton",
									"id": "btnPresetSave",
									"text": "e248",
									"x": 322.0,
									"y": 2.0,
									"width": 26.0,
									"height": 26.0,
									"textColour": 0xffcdd6f4,
									"parentComponent": "pnlPresetDisplay",
									"saveInPreset": "0",
									"tooltip": "Save Current Preset",
									"isMomentary": "1",
									"locked": "1",
									"enableMidiLearn": "0"
								}
							]
						},
						{
							"type": "ScriptSlider",
							"id": "knbMasterPan",
							"x": 785.0,
							"y": 17.0,
							"middlePosition": 0.0,
							"stepSize": 1.0,
							"min": -100.0,
							"max": 100.0,
							"suffix": "L",
							"parentComponent": "pnlHeader",
							"width": 60.0,
							"height": 16.0,
							"textColour": 0xffcdd6f4,
							"dragDirection": "Vertical",
							"showTextBox": "0",
							"text": "PAN",
							"mode": "Pan",
							"locked": "1",
							"tooltip": "Master Pan",
							"pluginParameterName": "Master Pan",
							"processorId": "masterGain",
							"parameterId": "Balance",
							"isPluginParameter": "0"
						},
						{
							"type": "ScriptSlider",
							"id": "knbMasterVolume",
							"x": 850.0,
							"y": 17.0,
							"middlePosition": -85.0,
							"stepSize": 1.0,
							"min": -100.0,
							"max": 0.0,
							"parentComponent": "pnlHeader",
							"width": 60.0,
							"height": 16.0,
							"textColour": 0xffcdd6f4,
							"dragDirection": "Vertical",
							"showTextBox": "0",
							"text": "VOL",
							"defaultValue": -3.0,
							"locked": "1",
							"tooltip": "Master Volume",
							"pluginParameterName": "Master Volume",
							"processorId": "masterGain",
							"parameterId": "Gain",
							"isPluginParameter": "0"
						},
						{
							"type": "ScriptFloatingTile",
							"id": "fltMasterPeak",
							"x": 915.0,
							"y": 20.0,
							"width": 75.0,
							"height": 10.0,
							"bgColour": 0xff050509,
							"itemColour": 0xff181825,
							"itemColour2": 0x0,
							"itemColour3": 0x0,
							"textColour": 0xff8993b6,
							"parentComponent": "pnlHeader",
							"ContentType": "MatrixPeakMeter",
            				"Data": "{\n  \"ProcessorId\": \"" + Synth.getIdList("Container")[0] + "\",\n  \"Index\": -1,\n  \"FollowWorkspace\": false,\n  \"SegmentLedSize\": 0.0,\n  \"UpDecayTime\": 0.0,\n  \"DownDecayTime\": 500.0,\n  \"UseSourceChannels\": false,\n  \"SkewFactor\": 0.2,\n  \"PaddingSize\": 1.0,\n  \"ShowMaxPeak\": true,\n  \"ChannelIndexes\": " + trace(channelIndexes) + "\n}",
							"locked": "1"
						},
						{
						  "type": "ScriptButton",
						  "id": "btnSettings",
						  "text": "e272",
						  "x": 680.0,
						  "y": 10.0,
						  "width": 30.0,
						  "height": 30.0,
						  "parentComponent": "pnlHeader",
						  "isMomentary": "1",
						  "tooltip": "Opens Settings Window",
						  "textColour": "4291679988",
						  "saveInPreset": "0",
						  "locked": 1						  
						},
						{
							"type": "ScriptPanel",
							"id": "pnlPreload",
							"x": 325.0,
							"y": 42.0,
							"width": 350.0,
							"height": 6.0,
							"bgColour": 0xff11111b,
							"textColour": 0xffcdd6f4,
							"parentComponent": "pnlHeader",
							"locked": "1",
							"visible": false
						}
					]
				},
				{
					"type": "ScriptPanel",
					"id": "pnlBody",
					"x": 0.0,
					"y": 50.0,
					"width": 1000.0,
					"height": 560.0,
					"bgColour": 0x0,
					"itemColour": 0xff1e1e2e,
					"itemColour2": 0xff1e1e2e,
					"textColour": 0x0,
					"borderSize": 0,
					"borderRadius": 0,
					"parentComponent": "pnlMain",
					"locked": "1"
				},
				{
					"type": "ScriptPanel",
					"id": "pnlFooter",
					"x": 0.0,
					"y": 610.0,
					"width": 1000.0,
					"height": 100.0,
					"bgColour": 0xff181825,
					"parentComponent": "pnlMain",
					"locked": "1",
					"childComponents": [
						{
						  "type": "ScriptFloatingTile",
						  "id": "fltPerformanceLabel",
						  "x": 44.0,
						  "y": 0.0,
						  "width": 300,
						  "height": 30,
						  "parentComponent": "pnlFooter",
						  "ContentType": "PerformanceLabel",
						  "bgColour": 0,
						  "itemColour": 0,
						  "itemColour2": 0,
						  "textColour": 4291679988,
						  "Font": "medium",
						  "FontSize": 12,
						  "locked": "1",
						},
						{
						  "type": "ScriptPanel",
						  "id": "pnlLogo",
						  "text": "",
						  "x": 350.0,
						  "y": 0,
						  "width": 300.0,
						  "height": 30.0,
						  "parentComponent": "pnlFooter",
						  "bgColour": 0,
						  "itemColour": 0,
						  "itemColour2": 0,
						  "textColour": 4291679988,
						  "borderSize": 0.0,
						  "borderRadius": 0.0
						},
						{
							"type": "ScriptFloatingTile",
							"id": "fltKeyboard",
							"ContentType": "Keyboard",
							"x": 44.0,
							"y": 30.0,
							"width": 912.0,
							"height": 65.0,
							"bgColour": 0xff06060a,
							"itemColour": 0x0,
							"itemColour2": 0x0,
							"itemColour3": 0x0,
							"textColour": 0xff000000,
							"Font": "medium",
							"FontSize": 9,
							"parentComponent": "pnlFooter",
							"locked": "1",
							"Data": "{\n  \"KeyWidth\": 16.0,\n  \"DisplayOctaveNumber\": false,\n  \"LowKey\": 12,\n  \"HiKey\": 108,\n  \"CustomGraphics\": false,\n  \"DefaultAppearance\": false,\n  \"BlackKeyRatio\": 0.64,\n  \"ToggleMode\": false,\n  \"MidiChannel\": 1,\n  \"UseVectorGraphics\": true,\n  \"UseFlatStyle\": true,\n  \"MPEKeyboard\": false,\n  \"MPEStartChannel\": 2,\n  \"MPEEndChannel\": 16\n}"
						}
					]
				},
				{
					"type": "ScriptPanel",
					"id": "pnlPresetBrowserContainer",
					"x": 0.0,
					"y": 50.0,
					"width": 1000.0,
					"height": 660.0,
					"parentComponent": "pnlMain",
					"locked": "1",
					"allowCallbacks": "Clicks Only",
					"visible": false,
					"childComponents": [
						{
							"type": "ScriptPanel",
							"id": "pnlPresetBrowser",
							"x": 50.0,
							"y": 5.0,
							"width": 900.0,
							"height": 500.0,
							"bgColour": 0xff313244,
							"locked": "1",
							"parentComponent": "pnlPresetBrowserContainer",
							"childComponents": [
								{
									"type": "ScriptFloatingTile",
									"id": "fltPresetBrowser",
									"x": 4.0,
									"y": 4.0,
									"width": 892.0,
									"height": 492.0,
									"bgColour": 0xff313244,
									"itemColour": 0xff1e1e2e,
									"itemColour2": 0x9a6c7086,
									"itemColour3": 0xff181823,
									"textColour": 0xffcdd6f4,	
									"font": "medium",
									"fontSize": 14,								
									"parentComponent": "pnlPresetBrowser",
									"ContentType": "PresetBrowser",
									"Data": "{\n  \"ShowSaveButton\": false,\n  \"ShowExpansionsAsColumn\": true,\n  \"ShowExpansionEditButtons\": true,\n  \"ShowExpansionContentOnly\": true,\n  \"ShowFolderButton\": true,\n  \"ShowNotes\": false,\n  \"ShowEditButtons\": true,\n  \"EditButtonOffset\": 10,\n  \"ShowAddButton\": true,\n  \"ShowRenameButton\": true,\n  \"ShowDeleteButton\": true,\n  \"ShowSearchBar\": true,\n  \"ShowFavoriteIcon\": true,\n  \"FavoriteIconOffset\": 6,\n  \"FullPathFavorites\": true,\n  \"FullPathSearch\": true,\n  \"ButtonsInsideBorder\": true,\n  \"NumColumns\": 3,\n  \"ColumnWidthRatio\": [\n    0.3,\n    0.23333333,\n    0.23333333,\n    0.23333333\n  ],\n  \"ListAreaOffset\": [\n    0,\n    0,\n    0,\n    0\n  ],\n  \"ColumnRowPadding\": [\n    30,\n    10,\n    10,\n    10\n  ],\n  \"SearchBarBounds\": [\n    611,\n    5,\n    276,\n    30\n  ],\n  \"MoreButtonBounds\": [\n    2,\n    5,\n    30,\n    30\n  ],\n  \"SaveButtonBounds\": [\n    846,\n    8,\n    50,\n    30\n  ],\n  \"FavoriteButtonBounds\": [\n    595,\n    8,\n    23,\n    23\n  ],\n  \"Type\": \"PresetBrowser\"\n}",
									"locked": "1",
								}
							]
						}
					]
				},
				{
					"type": "ScriptPanel",
					"id": "pnlSettingsContainer",
					"x": 0.0,
					"y": 0.0,
					"width": 1000.0,
					"height": 710.0,
					"parentComponent": "pnlMain",
					"locked": "1",
					"visible": false,
					"childComponents": [
						{
							"type": "ScriptPanel",
							"id": "pnlSettings",
							"x": 200.0,
							"y": 142.0,
							"width": 600.0,
							"height": 350.0,
							"bgColour": 0xff313244,
							"textColour": 0xffcdd6f4,
							"parentComponent": "pnlSettingsContainer",
							"text": "SETTINGS",
							"locked": "1",
							"childComponents": [
								{
									"type": "ScriptButton",
									"id": "btnSettingsClose",
									"x": 575.0,
									"y": 5.0,
									"text": "e4f6",
									"width": 20.0,
									"height": 20.0,
									"textColour": 0xffcdd6f4,
									"parentComponent": "pnlSettings",
									"saveInPreset": "0",
									"isMomentary": "1",
									"enableMidiLearn": "0",
									"locked": "1"
								},
								{
									"type": "ScriptedViewport",
									"id": "vptSettingsMenu",
									"x": 10.0,
									"y": 55.0,
									"width": 170.0,
									"height": 285.0,
									"parentComponent": "pnlSettings",
									"scrollBarThickness": "10.0",
									"saveInPreset": "0",
									"locked": "1",
									"childComponents": [
										{
											"type": "ScriptPanel",
											"id": "pnlSettingsMenu",
											"x": 0.0,
											"y": 0.0,
											"bgColour": 0x0,
											"itemColour": 0xff1e1e2e,
											"itemColour2": 0x0,
											"textColour": 0xffcdd6f4,
											"width": 160.0,
											"height": 200,
											"textColour": 0xffcdd6f4,
											"parentComponent": "vptSettingsMenu",
											"borderRadius": 5,
											"allowCallbacks": "All Callbacks",
											"locked": "1"
										}
									]
								},
								{
									"type": "ScriptPanel",
									"id": "pnlEngineSettingsContainer",
									"x": 200.0,
									"y": 30.0,
									"width": 400.0,
									"height": 320.0,
									"parentComponent": "pnlSettings",
									"text": "ENGINE",
									"locked": "1",
									"childComponents": [
										{
											"type": "ScriptedViewport",
											"id": "vptEngineSettings",
											"x": 0.0,
											"y": 0.0,
											"width": 380.0,
											"height": 300.0,
											"parentComponent": "pnlEngineSettingsContainer",
											"scrollBarThickness": "10.0",
											"locked": "1",
											"childComponents": [
												{
													"type": "ScriptPanel",
													"id": "pnlEngineSettings",
													"x": 0.0,
													"y": 0.0,
													"width": 370.0,
													"height": 200,
													"textColour": 0xffcdd6f4,
													"parentComponent": "vptEngineSettings",
													"locked": "1",
													"childComponents": [
														{
															"type": "ScriptComboBox",
															"id": "cmbStreamingMode",
															"x": 235,
															"y": 5.0,
															"max": 2,
															"width": 125.0,
															"height": 30.0,
															"bgColour": 0xff181825,
															"textColour": 0xffcdd6f4,
															"parentComponent": "pnlEngineSettings",
															"text": "Disk Mode",
															"items": "SSD\nHDD",
															"saveInPreset": "0",
															"locked": "1"
														},
														{
															"type": "ScriptComboBox",
															"id": "cmbMaxVoices",
															"x": 235,
															"y": 45.0,
															"max": 4,
															"width": 125.0,
															"height": 30.0,
															"bgColour": 0xff181825,
															"textColour": 0xffcdd6f4,
															"parentComponent": "pnlEngineSettings",
															"text": "Max Voices",
															"items": "32\n64\n128\n256",
															"saveInPreset": "0",
															"defaultValue": 4.0,
															"locked": "1"
														},
														{
															"type": "ScriptComboBox",
															"id": "cmbZoom",
															"x": 235,
															"y": 85.0,
															"max": 9,
															"width": 125.0,
															"height": 30.0,
															"bgColour": 0xff181825,
															"textColour": 0xffcdd6f4,
															"parentComponent": "pnlEngineSettings",
															"text": "UI Scale",
															"items": "0.75x\n1x\n1.5x\n2x\n2.5x\n3x\n4x\nCustom",
															"saveInPreset": "0",
															"defaultValue": 2.0,
															"locked": "1"
														},
														{
															"type": "ScriptPanel",
															"id": "pnlGlobalBpm",
															"x": 270,
															"y": 125.0,
															"width": 90.0,
															"height": 30.0,
															"bgColour": 0xff181825,
															"textColour": 0xffcdd6f4,
															"parentComponent": "pnlEngineSettings",
															"text": "BPM",
															"locked": "1",
															"childComponents": [
																{
																	"type": "ScriptSlider",
																	"id": "knbGlobalBpm",
																	"x": 15,
																	"y": 0,
																	"middlePosition": 120.0,
																	"stepSize": 1.0,
																	"min": 30.0,
																	"max": 240.0,
																	"width": 60,
																	"height": 30,
																	"parentComponent": "pnlGlobalBpm",
																	"text": "BPM",
																	"dragDirection": "Vertical",
																	"showTextBox": 0,
																	"defaultValue": 140.0,
																	"saveInPreset": "0",
																	"enableMidiLearn": false,
																	"locked": "1"
																}
															]
														},
														{
															"type": "ScriptButton",
															"id": "btnTooltips",
															"x": 326,
															"y": 170.0,
															"width": 34,
															"height": 20,
															"itemColour": 0xff8eff9d,
															"itemColour2": 0xffa3aed3,
															"textColour": 0xffcdd6f4,
															"parentComponent": "pnlEngineSettings",
															"text": "Show Tooltips",
															"saveInPreset": false,
															"enableMidiLearn": false,
															"defaultValue": 1.0,
															"locked": "1"
														}
													]
												}
											]
										}
									]
								},
								{
									"type": "ScriptPanel",
									"id": "pnlAudioSettings",
									"x": 200.0,
									"y": 30.0,
									"width": 400.0,
									"height": 320.0,
									"textColour": 0xffcdd6f4,
									"parentComponent": "pnlSettings",
									"text": "AUDIO",
									"locked": "1",
									"visible": false,
									"childComponents": [
										{
											"type": "ScriptFloatingTile",
											"id": "fltAudioSettings",
											"x": -5.0,
											"y": -10.0,
											"width": 424.0,
											"height": 288.0,
											"bgColour": 0xff181825,
											"textColour": 0xffcdd6f4,
											"parentComponent": "pnlAudioSettings",
											"ContentType": "CustomSettings",
											"Data": "{\n  \"Driver\": true,\n  \"Device\": true,\n  \"Output\": true,\n  \"BufferSize\": true,\n  \"SampleRate\": true,\n  \"GlobalBPM\": false,\n  \"StreamingMode\": false,\n  \"ScaleFactor\": false,\n  \"VoiceAmountMultiplier\": false,\n  \"ClearMidiCC\": false,\n  \"SampleLocation\": false,\n  \"DebugMode\": false,\n  \"UseOpenGL\": false,\n  \"ScaleFactorList\": [\n    0.5,\n    0.75,\n    1.0,\n    1.25,\n    1.5,\n    2.0\n  ], \n \"LabelAlignment\": \"left\"\n}",
											"locked": "1"
										}
									]
								},
								{
									"type": "ScriptPanel",
									"id": "pnlMidiSettings",
									"x": 200.0,
									"y": 30.0,
									"width": 400.0,
									"height": 320.0,
									"textColour": 0xffcdd6f4,
									"parentComponent": "pnlSettings",
									"text": "MIDI I/O",
									"locked": "1",
									"visible": false,
									"childComponents": [
									{
								        "type": "ScriptPanel",
								        "id": "pnlMidiChannels",
								        "x": 0.0,
								        "y": 22.0,
								        "width": 380.0,
								        "height": 80.0,
								        "itemColour": 0xff11111b,
								        "itemColour2": 0xff11111b,
								        "textColour": 0xffcdd6f4,
								        "parentComponent": "pnlMidiSettings",
								        "allowCallbacks": "All Callbacks",
								        "locked": "1",
								      },
								      {
								        "type": "ScriptFloatingTile",
								        "id": "fltMidiSources",
								        "x": -5.0,
								        "y": 140.0,
								        "width": 385.0,
								        "height": 160.0,
								        "itemColour": 0xff11111b,
								        "itemColour2": 0xff11111b,
								        "textColour": 0xffcdd6f4,
								        "parentComponent": "pnlMidiSettings",
								        "ContentType": "MidiSources",
								        "locked": "1",
								      }
									]
								},
								{
									"type": "ScriptPanel",
									"id": "pnlInstrumentSettingsContainer",
									"x": 200.0,
									"y": 30.0,
									"width": 400.0,
									"height": 320.0,
									"textColour": 0xffcdd6f4,
									"parentComponent": "pnlSettings",
									"text": "INSTRUMENT",
									"locked": "1",
									"visible": false,
									"childComponents": [
										{
											"type": "ScriptedViewport",
											"id": "vptInstrumentSettings",
											"x": 0.0,
											"y": 0.0,
											"width": 380.0,
											"height": 300.0,
											"parentComponent": "pnlInstrumentSettingsContainer",
											"saveInPreset": "0",
											"scrollBarThickness": "10.0",
											"locked": "1",
											"childComponents": [
												{
													"type": "ScriptPanel",
													"id": "pnlInstrumentSettings",
													"x": 0.0,
													"y": 0.0,
													"width": 370.0,
													"height": 200,
													"textColour": 0xffcdd6f4,
													"parentComponent": "vptInstrumentSettings",
													"locked": "1",
													"childComponents": [
														{
															"type": "ScriptPanel",
															"id": "pnlCoarseTune",
															"x": 270,
															"y": 5.0,
															"width": 90.0,
															"height": 30.0,
															"bgColour": 0xff181825,
															"textColour": 0xffcdd6f4,
															"parentComponent": "pnlInstrumentSettings",
															"text": "Coarse Tune",
															"locked": "1",
															"childComponents": [
																{
																	"type": "ScriptSlider",
																	"id": "knbCoarseTune",
																	"x": 15,
																	"y": 0,
																	"middlePosition": 0.0,
																	"stepSize": 1.0,
																	"min": -12.0,
																	"max": 12.0,
																	"suffix": " st",
																	"width": 60,
																	"height": 30,
																	"parentComponent": "pnlCoarseTune",
																	"text": "Coarse Tune",
																	"dragDirection": "Vertical",
																	"showTextBox": 0,
																	"pluginParameterName": "Coarse Tune",
																	"isPluginParameter": 0,
																	"processorId": "tuningHandler",
																	"parameterId": "CoarseTune",
																	"locked": "1"
																}
															]
														},
														{
															"type": "ScriptPanel",
															"id": "pnlFineTune",
															"x": 270,
															"y": 45.0,
															"width": 90.0,
															"height": 30.0,
															"bgColour": 0xff181825,
															"textColour": 0xffcdd6f4,
															"parentComponent": "pnlInstrumentSettings",
															"text": "Fine Tune",
															"locked": "1",
															"childComponents": [
																{
																	"type": "ScriptSlider",
																	"id": "knbFineTune",
																	"x": 15,
																	"y": 0,
																	"middlePosition": 0.0,
																	"stepSize": 1.0,
																	"min": -100.0,
																	"max": 100.0,
																	"suffix": " ct",
																	"width": 60,
																	"height": 30,
																	"parentComponent": "pnlFineTune",
																	"text": "Fine Tune",
																	"dragDirection": "Vertical",
																	"showTextBox": 0,
																	"pluginParameterName": "Fine Tune",
																	"isPluginParameter": 0,
																	"processorId": "tuningHandler",
																	"parameterId": "FineTune",
																	"locked": "1"
																}
															]
														},
														{
															"type": "ScriptPanel",
															"id": "pnlTranspose",
															"x": 270,
															"y": 85.0,
															"width": 90.0,
															"height": 30.0,
															"bgColour": 0xff181825,
															"textColour": 0xffcdd6f4,
															"parentComponent": "pnlInstrumentSettings",
															"text": "Transpose",
															"locked": "1",
															"childComponents": [
																{
																	"type": "ScriptSlider",
																	"id": "knbTranspose",
																	"x": 15,
																	"y": 0,
																	"middlePosition": 0.0,
																	"stepSize": 1.0,
																	"min": -6.0,
																	"max": 6.0,
																	"suffix": " st",
																	"width": 60,
																	"height": 30,
																	"parentComponent": "pnlTranspose",
																	"text": "Transpose",
																	"dragDirection": "Vertical",
																	"showTextBox": 0,
																	"isPluginParameter": 0,
																	"pluginParameterName": "Transpose",
																	"processorId": "tuningHandler",
																	"parameterId": "SemiToneTranspose",
																	"locked": "1"
																}
															]
														},
														{
															"type": "ScriptButton",
															"id": "btnLazyLoad",
															"x": 326,
															"y": 130.0,
															"width": 34,
															"height": 20,
															"itemColour": 0xff8eff9d,
															"itemColour2": 0xffa3aed3,
															"textColour": 0xffcdd6f4,
															"parentComponent": "pnlInstrumentSettings",
															"text": "Lazy Load",
															"tooltip": "Unloads samples until they are played",
															"enableMidiLearn": "0",
															"processorId": "samplerPurgeHandler",
															"parameterId": "LazyLoad",
															"locked": "1"
														},
														{
															"type": "ScriptButton",
															"id": "btnReleaseTriggers",
															"x": 326,
															"y": 170.0,
															"width": 34,
															"height": 20,
															"itemColour": 0xff8eff9d,
															"itemColour2": 0xffa3aed3,
															"textColour": 0xffcdd6f4,
															"parentComponent": "pnlInstrumentSettings",
															"text": "Release Triggers",
															"tooltip": "Enable or disable release triggers for articulations that use them",
															"enableMidiLearn": "0",
															"locked": "1"
														}
													]
												}
											]
										}
									]
								},
								{
									"type": "ScriptPanel",
									"id": "pnlMidiAutomation",
									"x": 200.0,
									"y": 35.0,
									"width": 390.0,
									"height": 290.0,
									"textColour": 0xffcdd6f4,
									"parentComponent": "pnlSettings",
									"text": "AUTOMATION",
									"locked": "1",
									"visible": false,
									"childComponents": [
										{
											"type": "ScriptFloatingTile",
											"id": "fltMidiAutomation",
											"x": 0.0,
											"y": 0.0,
											"width": 381.0,
											"height": 290.0,
											"parentComponent": "pnlMidiAutomation",
											"bgColour": 0x0,
											"itemColour": 0xff222233,
											"itemColour2": 0xff222233,
											"itemColour3": 0xff191929,
											"textColour": 0xffcdd6f4,
											"Font": "medium",
											"FontSize": 14,
											"ContentType": "MidiLearnPanel",
											"Data": "{\n  \"ColumnWidthRatio\": [\n    0.1,\n    0.44,\n    0.16,\n    0.15,\n    0.15\n  ],\n  \"ScrollbarWidth\": 10\n}",
											"locked": "1"
										}
									]
								},
								{
									"type": "ScriptPanel",
									"id": "pnlSettingsAbout",
									"x": 200.0,
									"y": 30.0,
									"width": 400.0,
									"height": 320.0,
									"textColour": 0xffcdd6f4,
									"parentComponent": "pnlSettings",
									"text": "ABOUT",
									"locked": "1"
								}
							]
						}
					]
				},
				{
					"type": "ScriptPanel",
					"id": "pnlTooltip",
					"x": 585.0,
					"y": 22.0,
					"width": 150.5586853027344,
					"height": 100.0,
				    "bgColour": 4279900710,
				    "itemColour": 4287863217,
				    "itemColour2": 0x0,
				    "textColour": 4291679988,
					"parentComponent": "pnlMain",
					"enabled": 0,
					"locked": "1",
					"visible": false
				},
				{
					"type": "ScriptPanel",
					"id": "pnlZoom",
					"x": 988,
					"y": 698,
					"parentComponent": "pnlMain",
					"width": 12,
					"height": 12,
					"textColour": 0xffcdd6f4,
					"allowCallbacks": "All Callbacks",
					"locked": "1"
				}
			]
		}
	]);
	
	if (Engine.isHISE())
		LayoutBuilder.process();
}
