/*
    Copyright 2024, 2025, 2026 David Healey

    This file is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This file is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with This file. If not, see <http://www.gnu.org/licenses/>.
*/

namespace Shell
{
	const style = CoreLookAndFeel.style;
	const fonts = style.fonts;
	const numSourceChannels = Synth.getRoutingMatrix(Synth.getIdList("Container")[0]).getNumSourceChannels();
	const channelIndexes = [];
	
	for (i = 0; i < numSourceChannels; i++)
		channelIndexes.push(i);

	LayoutBuilder.add([
	{
		"type": "ScriptPanel",
		"id": "pnlMain",
		"width": 1000.0,
		"height": 710.0,
		"locked": "1",
		"borderSize": 0.0,
		"borderRadius": 0.0,
		"childComponents": [{
			"type": "ScriptPanel",
			"id": "pnlHeader",
			"width": 1000.0,
			"height": 50.0,
			"parentComponent": "pnlMain",
			"locked": "1",
			"borderSize": 0.0,
			"borderRadius": 0.0,
			"childComponents": [{
				"type": "ScriptSlider",
				"id": "knbPatch",
				"width": 100.0,
				"height": 50.0,
				"parentComponent": "pnlHeader",
				"max": 100.0,
				"stepSize": 1.0,
				"middlePosition": 50.0,
				"processorId": "configurationHandler",
				"parameterId": "Patch",
				"enableMidiLearn": "0",
				"visible": "0",
				"locked": "1"
			},
			{
				"type": "ScriptSlider",
				"id": "knbArticulation",
				"x": 100.0,
				"width": 100.0,
				"height": 50.0,
				"parentComponent": "pnlHeader",
				"processorId": "configurationHandler",
				"parameterId": "Articulation",
				"max": 100.0,
				"stepSize": 1.0,
				"middlePosition": 50.0,
				"enableMidiLearn": "0",
				"visible": "0",
				"locked": "1"
			},
			{
				"type": "ScriptPanel",
				"id": "pnlPresetDisplay",
				"x": 325.0,
				"y": 10.0,
				"width": 350.0,
				"height": 30.0,
				"parentComponent": "pnlHeader",
				"borderSize": 1.0,
				"borderRadius": 2.0,
				"locked": "1",
				"childComponents": [{
					"type": "ScriptButton",
					"id": "btnPresetBrowser",
					"width": 289.0,
					"height": 30.0,
					"parentComponent": "pnlPresetDisplay",
					"saveInPreset": "0",
					"text": "Presets",
					"locked": "1",
					"enableMidiLearn": "0",
					"tooltip": "Click to Open Preset Browser"
				},
				{
					"type": "ScriptButton",
					"id": "btnPreset0",
					"x": 287.0,
					"width": 15.0,
					"height": 30.0,
					"parentComponent": "pnlPresetDisplay",
					"saveInPreset": "0",
					"isMomentary": "1",
					"text": "e138",
					"tooltip": "Load Previous Preset",
					"locked": "1",
					"enableMidiLearn": "0"
				},
				{
					"type": "ScriptButton",
					"id": "btnPreset1",
					"x": 304.0,
					"width": 15.0,
					"height": 30.0,
					"parentComponent": "pnlPresetDisplay",
					"saveInPreset": "0",
					"isMomentary": "1",
					"text": "e13a",
					"tooltip": "Load Next Preset",
					"locked": "1",
					"enableMidiLearn": "0"
				},
				{
					"type": "ScriptButton",
					"id": "btnPresetSave",
					"x": 322.0,
					"y": 2.0,
					"width": 26.0,
					"height": 26.0,
					"parentComponent": "pnlPresetDisplay",
					"saveInPreset": "0",
					"tooltip": "Save Current Preset",
					"text": "e248",
					"isMomentary": "1",
					"locked": "1",
					"enableMidiLearn": "0"
				}]
			},
			{
				"type": "ScriptSlider",
				"id": "knbMasterPan",
				"x": 780.0,
				"y": 14.0,
				"width": 65.0,
				"height": 22.0,
				"middlePosition": 0.0,
				"stepSize": 1.0,
				"min": -100.0,
				"max": 100.0,
				"suffix": "L",
				"parentComponent": "pnlHeader",
				"dragDirection": "Vertical",
				"text": "PAN",
				"mode": "Pan",
				"locked": "1",
				"tooltip": "Master Pan",
				"pluginParameterName": "Master Pan",
				"processorId": "masterGain",
				"parameterId": "Balance"
			},
			{
				"type": "ScriptSlider",
				"id": "knbMasterVolume",
				"x": 847.0,
				"y": 14.0,
				"width": 65.0,
				"height": 22.0,
				"middlePosition": -85.0,
				"stepSize": 1.0,
				"min": -100.0,
				"max": 0.0,
				"parentComponent": "pnlHeader",
				"dragDirection": "Vertical",
				"text": "VOL",
				"defaultValue": -3.0,
				"locked": "1",
				"tooltip": "Master Volume",
				"pluginParameterName": "Master Volume",
				"processorId": "masterGain",
				"parameterId": "Gain"
			},
			{
				"type": "ScriptFloatingTile",
				"id": "fltMasterPeak",
				"x": 915.0,
				"y": 20.0,
				"width": 75.0,
				"height": 10.0,
				"parentComponent": "pnlHeader",
				"ContentType": "MatrixPeakMeter",
				"Data": "{\n  \"ProcessorId\": \"" + Synth.getIdList("Container")[0] + "\",\n  \"Index\": -1,\n  \"FollowWorkspace\": false,\n  \"SegmentLedSize\": 0.0,\n  \"UpDecayTime\": 50.0,\n  \"DownDecayTime\": 500.0,\n  \"UseSourceChannels\": false,\n  \"SkewFactor\": 0.2,\n  \"PaddingSize\": 1.0,\n  \"ShowMaxPeak\": true,\n  \"ChannelIndexes\": " + trace(channelIndexes) + "\n}",
				"locked": "1"
			},
			{
				"type": "ScriptPanel",
				"id": "pnlPreload",
				"x": 325.0,
				"y": 42.0,
				"width": 350.0,
				"height": 6.0,
				"parentComponent": "pnlHeader",
				"text": "",
				"borderRadius": 1.0,
				"borderSize": 0.0,
				"locked": "1",
				"visible": false
			},
			{
				"type": "ScriptButton",
				"id": "btnSettings",
				"x": 682.0,
				"y": 13.0,
				"text": "e272",
				"width": 24.0,
				"height": 24.0,
				"parentComponent": "pnlHeader",
				"isMomentary": "1",
				"tooltip": "Opens Settings Window",
				"saveInPreset": "0",
				"locked": "1",
				"enableMidiLearn": "0"
			},
			{
				"type": "ScriptButton",
				"id": "btnRhapsody",
				"x": 10.0,
				"y": 15.0,
				"text": "e058",
				"width": 20.0,
				"height": 20.0,
				"parentComponent": "pnlHeader",
				"isMomentary": "1",
				"tooltip": "Unload this instrument",
				"saveInPreset": "0",
				"locked": "1",
				"enableMidiLearn": "0"
			}]
		},
		{
			"type": "ScriptPanel",
			"id": "pnlBody",
			"y": 50.0,
			"width": 1000.0,
			"height": 560.0,
			"parentComponent": "pnlMain",
			"locked": "1",
			"borderSize": 0.0,
			"borderRadius": 0.0
		},
		{
			"type": "ScriptPanel",
			"id": "pnlFooter",
			"y": 610.0,
			"width": 1000.0,
			"height": 100.0,
			"parentComponent": "pnlMain",
			"locked": "1",
			"borderSize": 0.0,
			"borderRadius": 0.0,
			"childComponents": [{
				"type": "ScriptPanel",
				"id": "pnlStatus",
				"width": 1000.0,
				"height": 30.0,
				"parentComponent": "pnlFooter",
				"borderSize": 0.0,
				"borderRadius": 0.0,
				"textColour": "0",
				"childComponents": [{
					"type": "ScriptFloatingTile",
					"id": "fltPerformanceLabel",
					"x": 46.0,
					"width": 300.0,
					"height": 30.0,
					"parentComponent": "pnlStatus",
					"ContentType": "PerformanceLabel",
					"Font": fonts.medium,
					"FontSize": 14 + fonts.size,
					"locked": "1"
				},
				{
					"type": "ScriptPanel",
					"id": "pnlLogo",
					"x": 350.0,
					"text": "",
					"width": 300.0,
					"height": 30.0,
					"parentComponent": "pnlStatus",
					"borderSize": 0.0,
					"borderRadius": 0.0
				}]
			},
			{
				"type": "ScriptFloatingTile",
				"id": "fltKeyboard",
				"x": 44.0,
				"y": 31.0,
				"width": 912.0,
				"height": 68.0,
				"parentComponent": "pnlFooter",
				"Font": "monoMedium",
				"FontSize": 10,
				"ContentType": "Keyboard",
				"Data": "{\n  \"KeyWidth\": 16.0,\n  \"DisplayOctaveNumber\": false,\n  \"LowKey\": 12,\n  \"HiKey\": 108,\n  \"CustomGraphics\": false,\n  \"DefaultAppearance\": false,\n  \"BlackKeyRatio\": 0.64,\n  \"ToggleMode\": false,\n  \"MidiChannel\": 1,\n  \"UseVectorGraphics\": true,\n  \"UseFlatStyle\": true,\n  \"MPEKeyboard\": false,\n  \"MPEStartChannel\": 2,\n  \"MPEEndChannel\": 16\n}"
			},
			{
			  "type": "ScriptButton",
			  "id": "btnAllNotesOff",
			  "x": 969.0,
			  "y": 56.0,
			  "width": 20.0,
			  "height": 20.0,
			  "parentComponent": "pnlFooter",
			  "text": "e4e2",
			  "tooltip": "Stop all MIDI Notes",
			  "saveInPreset": false,
			  "isMomentary": true
			}]
		},
		{
			"type": "ScriptPanel",
			"id": "pnlPresetBrowserContainer",
			"y": 50.0,
			"width": 1000.0,
			"height": 660.0,
			"parentComponent": "pnlMain",
			"locked": "1",
			"allowCallbacks": "Clicks Only",
			"visible": false,
			"childComponents": [{
				"type": "ScriptPanel",
				"id": "pnlPresetBrowser",
				"x": 50.0,
				"y": 5.0,
				"width": 900.0,
				"height": 500.0,
				"locked": "1",
				"borderRadius": 2.0,
				"parentComponent": "pnlPresetBrowserContainer",
				"borderSize": 1.0,
				"childComponents": [{
					"type": "ScriptFloatingTile",
					"id": "fltPresetBrowser",
					"x": 4.0,
					"y": 4.0,
					"width": 892.0,
					"height": 492.0,
					"parentComponent": "pnlPresetBrowser",
					"ContentType": "PresetBrowser",
					"Data": "{\n  \"ShowSaveButton\": false,\n  \"ShowExpansionsAsColumn\": false,\n  \"ShowFolderButton\": true,\n  \"ShowNotes\": false,\n  \"ShowEditButtons\": true,\n  \"EditButtonOffset\": 10,\n  \"ShowAddButton\": true,\n  \"ShowRenameButton\": true,\n  \"ShowDeleteButton\": true,\n  \"ShowSearchBar\": true,\n  \"ShowFavoriteIcon\": true,\n  \"FavoriteIconOffset\": 7,\n  \"FullPathFavorites\": true,\n  \"FullPathSearch\": true,\n  \"ButtonsInsideBorder\": true,\n  \"NumColumns\": 3,\n  \"ColumnWidthRatio\": [\n    0.3333333333333333,\n    0.3333333333333333,\n    0.3333333333333333\n  ],\n  \"ListAreaOffset\": [\n    0,\n    0,\n    0,\n    0\n  ],\n  \"ColumnRowPadding\": [\n    10,\n    10,\n    10,\n    10\n  ],\n  \"SearchBarBounds\": [\n    611,\n    5,\n    276,\n    30\n  ],\n  \"MoreButtonBounds\": [\n    2,\n    5,\n    30,\n    30\n  ],\n  \"SaveButtonBounds\": [\n    846,\n    8,\n    50,\n    30\n  ],\n  \"FavoriteButtonBounds\": [\n    595,\n    8,\n    23,\n    23\n  ],\n  \"Type\": \"PresetBrowser\"\n}",
					"locked": "1",
					"Font": "Oxygen",
					"FontSize": 14
				}]
			}]
		},
		{
			"type": "ScriptPanel",
			"id": "pnlSettingsContainer",
			"width": 1000.0,
			"height": 710.0,
			"parentComponent": "pnlMain",
			"locked": "1",
			"allowCallbacks": "Clicks Only",
			"visible": false,
			"childComponents": [{
				"type": "ScriptPanel",
				"id": "pnlSettings",
				"x": 200.0,
				"y": 142.0,
				"width": 600.0,
				"height": 350.0,
				"parentComponent": "pnlSettingsContainer",
				"borderSize": 0.0,
				"borderRadius": 2.0,
				"locked": "1",
				"childComponents": [				
				{
					"type": "ScriptedViewport",
					"id": "vptSettingsMenu",
					"x": 10.0,
					"y": 55.0,
					"width": 170.0,
					"height": 285.0,
					"parentComponent": "pnlSettings",
					"scrollBarThickness": "10.0",
					"saveInPreset": "0",
					"locked": "1",
					"childComponents": [{
						"type": "ScriptPanel",
						"id": "pnlSettingsMenu",
						"width": 160.0,
						"height": 240,
						"parentComponent": "vptSettingsMenu",
						"allowCallbacks": "All Callbacks",
						"borderSize": 0.0,
						"borderRadius": 2.0,
						"locked": "1"
					}]
				},
				{
					"type": "ScriptPanel",
					"id": "pnlEngineSettingsContainer",
					"x": 200.0,
					"y": 30.0,
					"width": 400.0,
					"height": 320.0,
					"parentComponent": "pnlSettings",
					"borderSize": 0.0,
					"borderRadius": 0.0,
					"text": "ENGINE",
					"locked": "1",
					"childComponents": [{
						"type": "ScriptedViewport",
						"id": "vptEngineSettings",
						"width": 380.0,
						"height": 300.0,
						"parentComponent": "pnlEngineSettingsContainer",
						"scrollBarThickness": "10.0",
						"saveInPreset": "0",
						"locked": "1",
						"childComponents": [{
							"type": "ScriptPanel",
							"id": "pnlEngineSettings",
							"width": 370.0,
							"height": 160,
							"parentComponent": "vptEngineSettings",
							"borderSize": 0.0,
							"borderRadius": 0.0,
							"locked": "1",
							"childComponents": [{
								"type": "ScriptComboBox",
								"id": "cmbStreamingMode",
								"x": 235,
								"y": 5.0,
								"max": 2,
								"width": 125.0,
								"height": 30.0,
								"parentComponent": "pnlEngineSettings",
								"text": "Disk Mode",
								"items": "SSD\nHDD",
								"saveInPreset": "0",
								"locked": "1"
							},
						{
							"type": "ScriptComboBox",
							"id": "cmbMaxVoices",
							"x": 235,
							"y": 45.0,
							"max": 4,
							"width": 125.0,
							"height": 30.0,
							"parentComponent": "pnlEngineSettings",
							"text": "Max Voices",
							"items": "32\n64\n128\n256",
							"saveInPreset": "0",
							"defaultValue": 4.0,
							"locked": "1"
						},
						{
							"type": "ScriptComboBox",
							"id": "cmbZoom",
							"x": 235,
							"y": 85.0,
							"max": 8,
							"width": 125.0,
							"height": 30.0,
							"parentComponent": "pnlEngineSettings",
							"text": "UI Scale",
							"saveInPreset": "0",
							"defaultValue": 2.0,
							"locked": "1"
						},
						{
							"type": "ScriptPanel",
							"id": "pnlGlobalBpm",
							"x": 270.0,
							"y": 125.0,
							"width": 90.0,
							"height": 30.0,
							"parentComponent": "pnlEngineSettings",
							"borderSize": 1.0,
							"borderRadius": 2.0,
							"text": "BPM",
							"locked": "1",
							"visible": "0",
							"childComponents": [{
								"type": "ScriptSlider",
								"id": "knbGlobalBpm",
								"x": 15.0,
								"middlePosition": 120.0,
								"stepSize": 1.0,
								"min": 30.0,
								"max": 240.0,
								"width": 60.0,
								"height": 30.0,
								"parentComponent": "pnlGlobalBpm",
								"text": "BPM",
								"dragDirection": "Vertical",
								"defaultValue": 120.0,
								"saveInPreset": "0",
								"locked": "1",
								"enableMidiLearn": "0"
							}]
						},
						{
							"type": "ScriptButton",
							"id": "btnLazyLoad",
							"x": 326,
							"y": 130.0,
							"width": 34,
							"height": 20,
							"parentComponent": "pnlEngineSettings",
							"text": "Lazy Load",
							"tooltip": "Unloads samples until they are played",
							"saveInPreset": "0",
							"enableMidiLearn": "0",
							"processorId": "samplerPurgeHandler",
							"parameterId": "LazyLoad",
							"locked": "1"
						},
						{
							"type": "ScriptButton",
							"id": "btnTooltips",
							"x": 326,
							"y": 130.0,
							"width": 34,
							"height": 20,
							"parentComponent": "pnlEngineSettings",
							"text": "Show Tooltips",
							"saveInPreset": "0",
							"enableMidiLearn": "0",
							"defaultValue": 1.0,
							"locked": "1"
						}]
					}]
				}]
				},
				{
					"type": "ScriptPanel",
					"id": "pnlAudioSettings",
					"x": 200.0,
					"y": 30.0,
					"width": 400.0,
					"height": 320.0,
					"parentComponent": "pnlSettings",
					"borderSize": 0.0,
					"borderRadius": 0.0,
					"text": "AUDIO",
					"locked": "1",
					"visible": false,
					"childComponents": [{
						"type": "ScriptFloatingTile",
						"id": "fltAudioSettings",
						"x": -5.0,
						"y": -10.0,
						"width": 424.0,
						"height": 288.0,
						"parentComponent": "pnlAudioSettings",
						"ContentType": "CustomSettings",
						"Data": "{\n  \"Driver\": true,\n  \"Device\": true,\n  \"Output\": true,\n  \"BufferSize\": true,\n  \"SampleRate\": true,\n  \"GlobalBPM\": false,\n  \"StreamingMode\": false,\n  \"ScaleFactor\": false,\n  \"VoiceAmountMultiplier\": false,\n  \"ClearMidiCC\": false,\n  \"SampleLocation\": false,\n  \"DebugMode\": false,\n  \"UseOpenGL\": false,\n  \"ScaleFactorList\": [\n    0.5,\n    0.75,\n    1.0,\n    1.25,\n    1.5,\n    2.0\n  ], \n \"LabelAlignment\": \"left\"\n}",
						"Font": fonts.medium,
						"FontSize": 16 + fonts.size,
						"locked": "1"
					}]
					},
					{
						"type": "ScriptPanel",
						"id": "pnlMidiSettings",
						"x": 200.0,
						"y": 30.0,
						"width": 400.0,
						"height": 320.0,
						"parentComponent": "pnlSettings",
						"borderSize": 0.0,
						"borderRadius": 0.0,
						"text": "MIDI I/O",
						"locked": "1",
						"visible": false,
						"childComponents": [{
							"type": "ScriptPanel",
							"id": "pnlMidiChannels",
							"y": 22.0,
							"width": 380.0,
							"height": 80.0,
							"parentComponent": "pnlMidiSettings",
							"allowCallbacks": "All Callbacks",
							"locked": "1",
							"bgColour": "0"
						},
						{
							"type": "ScriptFloatingTile",
							"id": "fltMidiSources",
							"x": -5.0,
							"y": 140.0,
							"width": 385.0,
							"height": 160.0,
							"parentComponent": "pnlMidiSettings",
							"ContentType": "MidiSources",
							"Font": fonts.medium,
							"FontSize": 16 + fonts.size,
							"locked": "1"
						}]
					},
					{
						"type": "ScriptPanel",
						"id": "pnlInstrumentSettingsContainer",
						"x": 200.0,
						"y": 30.0,
						"width": 400.0,
						"height": 320.0,
						"parentComponent": "pnlSettings",
						"borderSize": 0.0,
						"borderRadius": 0.0,
						"text": "INSTRUMENT",
						"locked": "1",
						"visible": false,
						"childComponents": [{
							"type": "ScriptedViewport",
							"id": "vptInstrumentSettings",
							"width": 380.0,
							"height": 300.0,
							"parentComponent": "pnlInstrumentSettingsContainer",
							"saveInPreset": "0",
							"scrollBarThickness": "10.0",
							"locked": "1",
							"childComponents": [{
								"type": "ScriptPanel",
								"id": "pnlInstrumentSettings",
								"width": 370.0,
								"height": 240,
								"parentComponent": "vptInstrumentSettings",
								"borderSize": 0.0,
								"borderRadius": 0.0,
								"locked": "1",
								"childComponents": [{
									"type": "ScriptPanel",
									"id": "pnlCoarseTune",
									"x": 270,
									"y": 5.0,
									"width": 90.0,
									"height": 30.0,
									"parentComponent": "pnlInstrumentSettings",
									"borderSize": 1.0,
									"borderRadius": 2.0,
									"text": "Coarse Tune",
									"locked": "1",
									"childComponents": [{
										"type": "ScriptSlider",
										"id": "knbCoarseTune",
										"x": 15,
										"y": 0,
										"middlePosition": 0.0,
										"stepSize": 1.0,
										"min": -12.0,
										"max": 12.0,
										"suffix": " st",
										"width": 60,
										"height": 30,
										"parentComponent": "pnlCoarseTune",
										"text": "Coarse Tune",
										"dragDirection": "Vertical",
										"processorId": "tuningHandler",
										"parameterId": "CoarseTune",
										"locked": "1",
										"pluginParameterName": "Coarse Tune"
									}]
								},
								{
									"type": "ScriptPanel",
									"id": "pnlFineTune",
									"x": 270,
									"y": 45.0,
									"width": 90.0,
									"height": 30.0,
									"parentComponent": "pnlInstrumentSettings",
									"borderSize": 1.0,
									"borderRadius": 2.0,
									"text": "Fine Tune",
									"locked": "1",
									"childComponents": [{
										"type": "ScriptSlider",
										"id": "knbFineTune",
										"x": 15,
										"y": 0,
										"middlePosition": 0.0,
										"stepSize": 1.0,
										"min": -100.0,
										"max": 100.0,
										"suffix": " ct",
										"width": 60,
										"height": 30,
										"parentComponent": "pnlFineTune",
										"text": "Fine Tune",
										"dragDirection": "Vertical",
										"processorId": "tuningHandler",
										"parameterId": "FineTune",
										"locked": "1",
										"pluginParameterName": "Fine Tune"
									}]
								},
								{
									"type": "ScriptPanel",
									"id": "pnlTranspose",
									"x": 270,
									"y": 85.0,
									"width": 90.0,
									"height": 30.0,
									"parentComponent": "pnlInstrumentSettings",
									"borderSize": 1.0,
									"borderRadius": 2.0,
									"text": "Transpose",
									"locked": "1",
									"childComponents": [{
										"type": "ScriptSlider",
										"id": "knbTranspose",
										"x": 15,
										"y": 0,
										"middlePosition": 0.0,
										"stepSize": 1.0,
										"min": -6.0,
										"max": 6.0,
										"suffix": " st",
										"width": 60,
										"height": 30,
										"parentComponent": "pnlTranspose",
										"text": "Transpose",
										"dragDirection": "Vertical",
										"processorId": "tuningHandler",
										"parameterId": "SemiToneTranspose",
										"locked": "1",
										"pluginParameterName": "Transpose"
									}]
								}]
							}]
						}]
					},
					{
						"type": "ScriptPanel",
						"id": "pnlAutomation",
						"x": 190.0,
						"y": 10.0,
						"width": 400.0,
						"height": 330.0,
						"parentComponent": "pnlSettings",
						"text": "AUTOMATION",
						"locked": "1",
						"allowCallbacks": "All Callbacks",
						"borderRadius": 2.0,
						"borderSize": 0.0,
						"visible": false,
						"childComponents": [{
							"type": "ScriptPanel",
							"id": "pnlMidiAutomation",
							"x": 0,
							"y": 35.0,
							"width": 400.0,
							"height": 285.0,
							"parentComponent": "pnlAutomation",
							"borderSize": 0.0,
							"borderRadius": 0.0,
							"childComponents": [{
								"type": "ScriptFloatingTile",
								"id": "fltMidiAutomation",
								"width": 400.0,
								"height": 285.0,
								"ContentType": "MidiLearnPanel",
								"Font": fonts.medium,
								"FontSize": 16 + fonts.size,
								"parentComponent": "pnlMidiAutomation",
								"locked": "1",
								"Data": "{\n  \"ColumnWidthRatio\": [\n    0.1,\n    0.44,\n    0.16,\n    0.15,\n    0.15\n  ],\n  \"RowHeight\": 30,\n  \"HeaderHeight\": 30,\n  \"ScrollbarWidth\": 10\n}",
							}]
						},
						{
							"type": "ScriptPanel",
							"id": "pnlMacros",
							"y": 35.0,
							"width": 400.0,
							"height": 295.0,
							"parentComponent": "pnlAutomation",
							"borderSize": 0.0,
							"borderRadius": 0.0,
							"visible": false,
							"childComponents": [{
								"type": "ScriptFloatingTile",
								"id": "fltMacros",
								"width": 400.0,
								"height": 285.0,
								"ContentType": "FrontendMacroPanel",
								"Font": fonts.medium,
								"FontSize": 16 + fonts.size,
								"parentComponent": "pnlMacros",
								"locked": "1",
								"Data": "{\n  \"ColumnWidthRatio\": [\n    0.13,\n    0.45,\n    0.16,\n    0.13,\n    0.13\n  ],\n  \"RowHeight\": 30,\n  \"HeaderHeight\": 30,\n  \"ScrollbarWidth\": 10\n}"
							}]
						},
						{
							"type": "ScriptPanel",
							"id": "pnlMpe",
							"y": 35.0,
							"width": 400.0,
							"height": 295.0,
							"parentComponent": "pnlAutomation",
							"borderSize": 0.0,
							"borderRadius": 0.0,
							"visible": false,
							"childComponents": [{
								"type": "ScriptedViewport",
								"id": "vptMpe",
								"width": 400.0,
								"height": 295.0,
								"parentComponent": "pnlMpe",
								"scrollBarThickness": "10.0",
								"fontName": fonts.medium,
								"fontSize": 16 + fonts.size
							}]
						}]
					},
					{
						"type": "ScriptPanel",
						"id": "pnlSettingsAbout",
						"x": 200.0,
						"y": 30.0,
						"width": 400.0,
						"height": 320.0,
						"parentComponent": "pnlSettings",
						"text": "ABOUT",
						"locked": "1",
						"visible": false
					},
					{
						"type": "ScriptButton",
						"id": "btnSettingsClose",
						"text": "e4f6",
						"x": 575.0,
						"y": 5.0,
						"width": 20.0,
						"height": 20.0,
						"parentComponent": "pnlSettings",
						"saveInPreset": "0",
						"isMomentary": "1",
						"enableMidiLearn": "0",
						"locked": "1"
					}]
				}]
			},
			{
				"type": "ScriptPanel",
				"id": "pnlTooltip",
				"x": 580.0,
				"y": 23.0,
				"width": 227.0,
				"height": 80.0,
				"parentComponent": "pnlMain",
				"enabled": 0,
				"borderRadius": 0.0,
				"borderSize": 1.0,
				"locked": "1",
				"itemColour2": "0",
				"visible": false,
				"tooltip": "Opens Settings Window"
			},
			{
				"type": "ScriptPanel",
				"id": "pnlZoom",
				"x": 988,
				"y": 698,
				"parentComponent": "pnlMain",
				"width": 12,
				"height": 12,
				"allowCallbacks": "All Callbacks",
				"locked": "1",
				"borderSize": 0.0,
				"borderRadius": 0.0
			}]
		}]
	);

	if (Engine.isHISE())
		LayoutBuilder.process();
}
